name: ${project.name}
main: ${project.groupId}.${project.artifactId}.BiomeCompass
version: ${project.version}
authors: [steffansk1997]
description: >
             Biome Compass
commands:
   bcompass:
      description: Retrieve a biome compass.
      usage: /bcompass
      permission: bcompass.get
      permission-message: You don't have <permission>