name: ${project.name}
main: ${project.groupId}.BiomeCompass
version: ${project.version}
authors: [steffansk1997]
description: Biome Compass
api-version: 1.15
commands:
  bcompass:
    description: Retrieve a biome compass.
    usage: /bcompass